version: "3.8"
services:
  db:
    image: postgres:15
    container_name: smartcampus_db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
      POSTGRES_DB: smartcampusdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./smartcampus
      dockerfile: Dockerfile
    container_name: smartcampus-site
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: smartcampusdb
      DB_USER: student
      DB_PASSWORD: student123
    ports:
      - "8000:8000"
volumes:
  db_data:
